
import { Inter } from "next/font/google";

import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/Header";
import { Footer7 } from "@/components/ui/Footer7";



const inter = Inter({subsets:["latin"]});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning >
      <body
        className="{`${inter.className}`}">
       <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <Header />
          <main className="min-h-screen" >{children}</main> 
          < Footer7 />
          </ThemeProvider>
      </body>
    </html>
  );
}
